[package]
name = "evdev-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# https://github.com/emberian/evdev
evdev = {version="0.12.0", features = ["tokio"]}
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3.24"
